FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Set environment variable to avoid issues with watching files
ENV CHOKIDAR_USEPOLLING=true

# Start application
CMD ["npm", "start"]
